In [1]:
import sys
from matplotlib import rcParams 
rcParams["figure.figsize"] = (16,5)
sys.path.append('')

import librosa
import librosa.display

from TTS.tts.models.tacotron2 import Tacotron2 
from TTS.tts.utils import *
from TTS.tts.utils.generic_utils import setup_model
from TTS.utils.audio import AudioProcessor
from TTS.utils.io import load_config
from TTS.tts.utils.text import text_to_sequence, phoneme_to_sequence
from TTS.tts.utils.text.symbols import symbols, phonemes
import torch
from TTS.tts.utils.synthesis import synthesis
import numpy as np

In [2]:
# Set constants

# MODEL_PATH = '/content/drive/MyDrive/Mestrado/TTS/GST_rosana_only/checkpoint_120000.pth.tar'
CONFIG_PATH =  './experiments/debug_add_emb/config.json'

# MODEL_PATH ='/content/drive/MyDrive/Mestrado/TTS/GST_3speaker_CPQD/best_model.pth.tar'
# CONFIG_PATH = '/content/drive/MyDrive/Mestrado/TTS/GST_3speaker_CPQD/config.json'

CONFIG = load_config(CONFIG_PATH)
# CONFIG['datasets'][0]['path'] = './'
# CONFIG['output_path'] = './'
# CONFIG['audio']['signal_norm'] = False
# CONFIG['audio']['stats_path'] = ''
# CONFIG['use_phonemes'] = False
# CONFIG['save_step'] = 500
CONFIG['num_prosodic_features'] = 0
CONFIG['agg_style_space'] = False
CONFIG['lookup_speaker_dim'] = 512
CONFIG['use_style_lookup'] = False
CONFIG['lookup_style_dim'] = 64
CONFIG['use_prosodic_linear'] = False
CONFIG['prosodic_dim'] = 2
use_cuda = False

# load the model
ap = AudioProcessor(**CONFIG.audio)

num_chars = len(phonemes) if CONFIG.use_phonemes else len(symbols)


# load the model
num_chars = len(phonemes) if CONFIG.use_phonemes else len(symbols)
model = setup_model(num_chars, 3, 2, CONFIG, None)

 > Setting up Audio Processor...
 | > sample_rate:16000
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:7600.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:
 | > hop_length:256
 | > win_length:1024
 > Using model: Tacotron2
Training with 3 speakers and 2 styles
Use style target = False
Use semi supervised = False


In [3]:
print(model)

Tacotron2(
  (speaker_embedding): Embedding(3, 512)
  (embedding): Embedding(217, 512, padding_idx=0)
  (encoder): Encoder(
    (convolutions): ModuleList(
      (0): ConvBNBlock(
        (convolution1d): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,))
        (batch_normalization): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (dropout): Dropout(p=0.5, inplace=False)
        (activation): ReLU()
      )
      (1): ConvBNBlock(
        (convolution1d): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,))
        (batch_normalization): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (dropout): Dropout(p=0.5, inplace=False)
        (activation): ReLU()
      )
      (2): ConvBNBlock(
        (convolution1d): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,))
        (batch_normalization): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
   

In [4]:
model._add_speaker_embedding

<function TTS.tts.models.tacotron_abstract.TacotronAbstract._add_speaker_embedding(outputs, speaker_embeddings)>

In [5]:
import numpy as np

s = "ambulantes vendem os ingressos para a copa do mundo de dois mil e catorze , mas só alguns dias antes do dia do sorteio ."

def text_to_seqvec(text, CONFIG):
    text_cleaner = [CONFIG.text_cleaner]
    # text ot phonemes to sequence vector
    if CONFIG.use_phonemes:
        seq = np.asarray(
            phoneme_to_sequence(text, text_cleaner, CONFIG.phoneme_language,
                                CONFIG.enable_eos_bos_chars,
                                tp=CONFIG.characters if 'characters' in CONFIG.keys() else None),
            dtype=np.int32)
    else:
        seq = np.asarray(text_to_sequence(text, text_cleaner, tp=CONFIG.characters if 'characters' in CONFIG.keys() else None), dtype=np.int32)
    return seq


def numpy_to_torch(np_array, dtype, cuda=False):
    if np_array is None:
        return None
    tensor = torch.as_tensor(np_array, dtype=dtype)
    if cuda:
        return tensor.cuda()
    return tensor

def id_to_torch(speaker_id, cuda=False):
    if speaker_id is not None:
        speaker_id = np.asarray(speaker_id)
        speaker_id = torch.from_numpy(speaker_id).unsqueeze(0)
    if cuda:
        return speaker_id.cuda().type(torch.long)
    return speaker_id.type(torch.long)

def compute_style_mel(style_wav, ap, cuda=False):
    style_mel = torch.FloatTensor(ap.melspectrogram(
        ap.load_wav(style_wav, sr=ap.sample_rate))).unsqueeze(0)
    if cuda:
        return style_mel.cuda()
    return style_mel

In [6]:
speaker_id = id_to_torch(2, cuda=use_cuda)

inputs = text_to_seqvec(s, CONFIG)
inputs = numpy_to_torch(inputs, torch.long, cuda=use_cuda)
inputs = inputs.unsqueeze(0)

x = model.embedding(inputs).transpose(1, 2)
x = model.encoder.inference(x)

In [7]:
speaker_ids = speaker_id
gst = True
num_speakers = 3
style_mel = None

if gst:
    # B x gst_dim
    inputs, encoder_outputs, logits = model.compute_gst(x,
                                       style_mel,
                                       speaker_embeddings if model.gst_use_speaker_embedding else None, style_agg = 'add')
# if num_speakers > 1:
#     if not model.embeddings_per_sample:
#         speaker_embeddings = model.speaker_embedding(speaker_ids)[:, None]
#     encoder_outputs = model._concat_speaker_embedding(encoder_outputs, speaker_embeddings)

entered None


In [8]:

encoder_outputs.shape

torch.Size([1, 1, 512])

In [9]:
rand = torch.rand(1, 1, 512)
model._add_speaker_embedding(encoder_outputs, rand).shape

torch.Size([1, 1, 512])

In [10]:
vetor_A = [1,1,1,1]
vetor_B = [0,1,4,1]

vetor_A = torch.Tensor(vetor_A)
vetor_B = torch.Tensor(vetor_B)

vetor_A = vetor_A.unsqueeze(0).unsqueeze(1)

vetor_B = vetor_B.unsqueeze(0)

print(vetor_A.shape, vetor_B.shape)

model._add_speaker_embedding(vetor_A, vetor_B),model._add_speaker_embedding(vetor_A, vetor_B).shape 

torch.Size([1, 1, 4]) torch.Size([1, 4])


(tensor([[[1., 2., 5., 2.]]]), torch.Size([1, 1, 4]))

In [11]:
import torch.nn.functional as F
F.normalize

<function torch.nn.functional.normalize(input, p=2, dim=1, eps=1e-12, out=None)>

In [12]:
F.normalize(vetor_A, dim = -1)

tensor([[[0.5000, 0.5000, 0.5000, 0.5000]]])

In [13]:
F.normalize(vetor_B, dim = -1)

tensor([[0.0000, 0.2357, 0.9428, 0.2357]])

In [14]:
! python TTS/bin/train_tts.py --config_path "./experiments/debug_add_emb/config.json" --experiment_folder "./experiments/debug_add_emb/" --continue_path ""

 > Using CUDA:  True
 > Number of GPUs:  1

 > Setting up Audio Processor...
 | > sample_rate:16000
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:7600.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:
 | > hop_length:256
 | > win_length:1024
 | > Found 10 files in D:\Mestrado\Emotion Audio Synthesis (TTS)\repo_final\pt_etts\experiments\debug_linear_logits
Training with 2 speakers: marco, rosana
Training with 2 styles + neutral: happy, neutral
 > Using model: Tacotron2
Training with 2 speakers and 2 styles
Use style target = False
Use semi supervised = False

 > Model has 60796308 parameters

 > EPOCH: 0/3

 > Number of output frames: 7

 > Data

Traceback (most recent call last):
  File "TTS/bin/train_tts.py", line 888, in <module>
    main(args)
  File "TTS/bin/train_tts.py", line 756, in main
    global_step, epoch, amp, speaker_mapping, style_mapping)
  File "TTS/bin/train_tts.py", line 202, in train
    for num_iter, data in enumerate(data_loader):
  File "C:\Users\lucas\Anaconda3\envs\m_audio\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "C:\Users\lucas\Anaconda3\envs\m_audio\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\lucas\Anaconda3\envs\m_audio\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "C:\Users\lucas\Anaconda3\envs\m_audio\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\lucas\Anaconda3\envs\m_audio\lib\multiprocessing\context.py", line 223, in _Pope